spring.datasource.url=jdbc:mysql://localhost:3306/careerbridge
spring.datasource.username=root
spring.datasource.password=Priscilla@Ngina

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

